### ISSUE TITLE
Add `org.opencontainers.image.source` to published image

### ISSUE THREAD

**Issue by ChristianCiach** [ph4r5h4d/wait4it#170]
Renovate uses the label `org.opencontainers.image.source` to retrieve the release notes for an image: https://docs.renovatebot.com/modules/datasource/docker/

This label should be set to the URL to this project: `https://github.com/ph4r5h4d/wait4it`. 

This enables Renovate to include the release notes of the GitHub release into the generated PRs.

**Comment by ph4r5h4d** [comment]
@ChristianCiach this is interesting, thanks for bringing it, I'll try to update the Dockerfile.

**Comment by ph4r5h4d** [comment]
Addressed in : https://github.com/ph4r5h4d/wait4it/releases/tag/v13.0.3

**Comment by ChristianCiach** [comment]
Unfortunately it still doesn't work and I've put way too much time into debugging the reason :)

I am pretty sure I've found the issue: Renovate first extracts the "version" from the image tag, for example `13.0.2` from `13.0.2-scratch`. It *then* tries to find updated images for this version, but it doesn't find any because there are no images with tags `13.0.3` or `13.0.4`.

So why does it work with so many other images that are using a similar tagging style, like Renovate's own `docker.io/renovate/renovate:39.251.1-full`? Because for every `renovate:39.251.1-full` there is also a `renovate:39.251.1`.

This is obviously a bug in Renovate, but I cannot bother creating an issue there, because creating a reproducible example is too much work. 

@ph4r5h4d You could make your project more "renovate compatible" by adding image tags like `ph4r5h4d/wait4it:13.0.2` as an alias for `ph4r5h4d/wait4it:13.0.2-scratch`. I would actually like to see this anyway, because the `-scratch` suffix seems redundant. I think there should be an *opinionated* version without suffix for people who don't really care about the base image (which should be most users).
